### ISSUE TITLE
Load order conflict with enchantment perk Twin Moons

### ISSUE THREAD

**Issue by catapsis** [erri120/lotus#74]
**Describe the bug**
The Twin Moons perk near the top of the Enchantment perk tree claims that there's a load order conflict.

**To Reproduce**
1. Go to the top of the Enchantment perk tree.
2. Find the Twin Moons perk.
3. Read the perk description.

**Expected behavior**
Perk description should indicate the function of the perk.

**Screenshots**
![enb2020_5_7_16_31_13_edit](https://user-images.githubusercontent.com/62223653/81351314-402b9380-9081-11ea-8025-a0b3d72bf1e1.jpg)

**Modlist version**
0.3

**Did you add any additional mods?**
Fertility Mode

**Comment by lordkabal26** [comment]
Put simply it's the smashed patch, it catches Adamant first but Path of Sorcery loads after it. the smashed patch didn't forward the path of sorcery description or anything else for that matter.

SSEEdit image:
![SSEEdit_U70OZdgHqG](https://user-images.githubusercontent.com/6248212/81392177-4440cb00-90ec-11ea-9cdd-8d451e233df5.png)

Solution is easy forward the data from Path of Sorcery into a custom patch using a new espl file but it'll likely be fixed in the next update

**Comment by erri120** [comment]
Fixed in the next update
