### ISSUE TITLE
Pure white structures in Dawnstar

### ISSUE THREAD

**Issue by Dave0523** [erri120/lotus#92]
**Describe the bug**
There are some structures added by JK's Slyrim in Dawnstar that are a pure white color.

**To Reproduce**
1. Go to Dawnstar
2. Look around

**Expected behavior**
Wooden textured structures

**Screenshots**
![ScreenShot200](https://user-images.githubusercontent.com/61605473/81693031-4b8a1080-942d-11ea-983d-d27c11c4a2bb.png)

**Modlist version**
0.3.2 HotFix

**Did you add any additional mods?**
No

**Comment by jyysn** [comment]
Disabling 'Illustrious Whiterun - Parallax Meshes' fixes this issue. I think it's missing the snow textures for those structures maybe?

**Comment by harrythehamster** [comment]
I have the same issue with structures in Dawnstar and some other structures

**Comment by sirlach** [comment]
@erri120 - According to Illustrious Whiterun in order to get Parralax meshes working you need to install SSE [Parallax Shader Fix (BETA)](https://www.nexusmods.com/skyrimspecialedition/mods/31963?tab=description) and a dll as well. I installed it and the DLL  in the last essentials slot and according to the log it appears to be running but this issue is still there. 

Reading through the [comments](https://www.nexusmods.com/skyrimspecialedition/mods/28950?tab=posts) on the Illustrious Whiterun page this is a known incompatibility with JK's Skyrim. Apparently JK reuses some Whiterun Textures in Dawnstar and this causes the issue.
