### ISSUE TITLE
Tembtra Armor Not Visible

### ISSUE THREAD

**Issue by SirDrake87** [erri120/lotus#97]
**Describe the bug**
Tembtra Armor Not Visible

**To Reproduce**
1. Find NPC wearing the armor.
2. Laugh at the floating head

**Expected behavior**
The armor to be visible

**Screenshots**
![enb2020_5_14_09_37_04](https://user-images.githubusercontent.com/65056112/82148014-4951f880-9817-11ea-92d1-575d5b210538.jpg)
![enb2020_5_14_09_37_28](https://user-images.githubusercontent.com/65056112/82148016-4b1bbc00-9817-11ea-9528-03fc52447936.jpg)

**Modlist version**
3.2

**Did you add any additional mods?**
Extra SLAL animations only.

**Comment by SirDrake87** [comment]
The Wild Armor does this as well.

**Comment by mael5trum** [comment]
A bunch of DeserterX armors do this as they are included in the Enemy Variations - Items esp but the mods themselves are not included, I'm guessing it's cause "DX CBBE 3BBB BodySlide Emporium SSE" doesn't have bodyslides for them.
I would assume the fix is to delete the records that mention the unavailable armors in the Enemy Variation - items esp?

**Comment by SirDrake87** [comment]
Update DX CBBE 3BBB BodySlide Emporium SSE to 1.2. Your version is 1.11

I added the extra DX armors as well.
